name: Assignment 2

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymysql

    - name: Run Python script
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        python automate_schema_changes.py ${{ env.DB_HOST }} ${{ env.DB_USER }} ${{ env.DB_PASSWORD }} ${{ env.DB_NAME }}